# Generated by Django 5.0.6 on 2024-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
